# Generated by Django 5.0.3 on 2024-03-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25, null=True)),
                ('lastname', models.CharField(max_length=25, null=True)),
                ('username', models.CharField(max_length=50, null=True, unique=True)),
                ('email', models.EmailField(max_length=60, null=True, unique=True)),
                ('phone', models.IntegerField(null=True, unique=True)),
                ('password', models.CharField(max_length=12, null=True)),
                ('bloodgroup', models.CharField(max_length=5, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
